config/routes.rb
Rails.application.routes.draw do
  resources :pdialunos
  resources :alunos
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/pdialuno.rb
class Pdialuno < ActiveRecord::Base
  belongs_to :aluno
end

app/controllers/pdialunos_controller.rb
class PdialunosController < ApplicationController
  before_action :set_pdialuno, only: [:show, :edit, :update, :destroy]

  # GET /pdialunos
  # GET /pdialunos.json
  def index
     @pdialunos = Pdialuno.all.paginate(page: params[:page], per_page:10)
  end

  # GET /pdialunos/1
  # GET /pdialunos/1.json
  def show
  end

  # GET /pdialunos/new
  def new
    @pdialuno = Pdialuno.new
  end

  # GET /pdialunos/1/edit
  def edit
  end

  # POST /pdialunos
  # POST /pdialunos.json
  def create
    @pdialuno = Pdialuno.new(pdialuno_params)

    respond_to do |format|
      if @pdialuno.save
        format.html { redirect_to @pdialuno, notice: 'Pdialuno was successfully created.' }
        format.json { render :show, status: :created, location: @pdialuno }
      else
        format.html { render :new }
        format.json { render json: @pdialuno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pdialunos/1
  # PATCH/PUT /pdialunos/1.json
  def update
    respond_to do |format|
      if @pdialuno.update(pdialuno_params)
        format.html { redirect_to @pdialuno, notice: 'Pdialuno was successfully updated.' }
        format.json { render :show, status: :ok, location: @pdialuno }
      else
        format.html { render :edit }
        format.json { render json: @pdialuno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pdialunos/1
  # DELETE /pdialunos/1.json
  def destroy
    @pdialuno.destroy
    respond_to do |format|
      format.html { redirect_to pdialunos_url, notice: 'Pdialuno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pdialuno
      @pdialuno = Pdialuno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pdialuno_params
      params.require(:pdialuno).permit(:a_interesse, :a_antencao, :a_concentracao, :a_compreencao, :a_habilidades, :a_pensamento, :a_expressao, :a_linguagem, :a_percepcoes, :a_diferenca, :a_espacial, :aluno_id)
    end
end

app/helpers/pdialunos_helper.rb
module PdialunosHelper
end

app/views/pdialunos/_form.html.erb
<%= simple_form_for(@pdialuno) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :a_interesse %>
    <%= f.input :a_antencao %>
    <%= f.input :a_concentracao %>
    <%= f.input :a_compreencao %>
    <%= f.input :a_habilidades %>
    <%= f.input :a_pensamento %>
    <%= f.input :a_expressao %>
    <%= f.input :a_linguagem %>
    <%= f.input :a_percepcoes %>
    <%= f.input :a_diferenca %>
    <%= f.input :a_espacial %>
    <%= f.association :aluno %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pdialunos/edit.html.erb
<h1>Editing Pdialuno</h1>

<%= render 'form' %>

<%= link_to 'Show', @pdialuno %> |
<%= link_to 'Back', pdialunos_path %>

app/views/pdialunos/index.html.erb
<%- model_class = Pdialuno -%><br>
<div class="panel panel-default" style="width: 80%; margin: 0 auto; ">
  <div class="panel-body"><h2> Listando PDI-Alunos</h2>
      <tr><%= will_paginate @pdialuno, renderer: BootstrapPagination::Rails %></tr>
    <table class="table table-striped" >
      <thead>
        <tr>
          <th><%= 'Código' %></th>
          <th><%= 'Código PDI-Alunos' %></th>
          <th><%= 'Código Aluno' %></th>
        </tr>
      </thead>
      <tbody>
        <% @pdialunos.each do |pdialuno| %>
          <tr>
            <td width: 5% ><%= link_to pdialuno.id, pdialuno_path(pdialuno),:size => 13 %></td>
            <td width: 5%><%= pdialuno.id %></td>
            <td width: 5% ><%= pdialuno.aluno_id %></td>
              <%= @pdialuno.aluno %>


            <td width: 5% >
              <%= link_to 'Mostrar',pdialuno_path(pdialuno), :class => 'btn btn-primary btn-sm' %>
              <%= link_to 'Editar',edit_pdialuno_path(pdialuno), :class => 'btn btn-success btn-sm' %>
              <%= link_to 'Apagar',pdialuno_path(pdialuno),:method => :delete, data: { confirm: 'Você tem certeza?'},:class => 'btn btn-danger btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>
      <div class="panel panel-default">
        <div class="panel-body">
            <%= link_to 'Incluir novo PDI-Aluno',new_pdialuno_path,:class => 'btn btn-primary' %>
        </div>
      </div>

</div>

app/views/pdialunos/new.html.erb
<h1>New Pdialuno</h1>

<%= render 'form' %>

<%= link_to 'Back', pdialunos_path %>

app/views/pdialunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>A interesse:</strong>
  <%= @pdialuno.a_interesse %>
</p>

<p>
  <strong>A antencao:</strong>
  <%= @pdialuno.a_antencao %>
</p>

<p>
  <strong>A concentracao:</strong>
  <%= @pdialuno.a_concentracao %>
</p>

<p>
  <strong>A compreencao:</strong>
  <%= @pdialuno.a_compreencao %>
</p>

<p>
  <strong>A habilidades:</strong>
  <%= @pdialuno.a_habilidades %>
</p>

<p>
  <strong>A pensamento:</strong>
  <%= @pdialuno.a_pensamento %>
</p>

<p>
  <strong>A expressao:</strong>
  <%= @pdialuno.a_expressao %>
</p>

<p>
  <strong>A linguagem:</strong>
  <%= @pdialuno.a_linguagem %>
</p>

<p>
  <strong>A percepcoes:</strong>
  <%= @pdialuno.a_percepcoes %>
</p>

<p>
  <strong>A diferenca:</strong>
  <%= @pdialuno.a_diferenca %>
</p>

<p>
  <strong>A espacial:</strong>
  <%= @pdialuno.a_espacial %>
</p>

<p>
  <strong>Aluno:</strong>
  <%= @pdialuno.aluno %>
</p>

<%= link_to 'Edit', edit_pdialuno_path(@pdialuno) %> |
<%= link_to 'Back', pdialunos_path %>