config/routes.rb
Rails.application.routes.draw do
  resources :pdialunos
  resources :alunos
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
  validates_presence_of :nome
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all.paginate(page: params[:page], per_page:10)
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  
    @alunos = Aluno.find(params[:id])

    respond_to do |format|
    format.html #show.html
    format.js
    format.json { render :json => @host }
    end
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(
        :nome, :celular, :telefone, :ativo, :endereco, :numero, :bairro, :cidade, :estado, :email, :data_nascimento, :data_cadastro, :cpf, :rg,
        
        :nome_pai,:endereco_pai,:numero_pai,:bairro_pai,:cidade_pai,:estado_pai,:data_nascimento_pai,:escolaridade_pai,:profissao_pai,:telefone_pai, :rg_pai, :cpf_pai, :obs_pai,
        
        :nome_mae,:endereco_mae,:numero_mae,:bairro_mae,:cidade_mae,:estado_mae,:data_nascimento_mae,:escolaridade_mae,:profissao_mae,:telefone_mae, :rg_mae, :cpf_mae, :obs_mae , 
        
        :escolar_trocas, :escolar_fala_atual , :escolar_ordens , :escolar_idade , :escolar_numero_escolas ,:escolar_aproveitamento , :escolar_comportamento , :escolar_frequenta_escola , :escolar_vida_escolar, :escolar_vida_social,
        :escolar_vive , :escolar_ambiente_familiar, :escolar_distrair, :escolar_amigos,

        :saude_medicacao, :saude_acompanhamento_medico, :saude_nome_medico, :saude_fono, :saude_psico, :saude_fisio, :saude_outros, :saude_tempo, :saude_observacoes, :saude_alergia, 
        :saude_convenio, :saude_tem_convenio, 

        :beneficio_bpc, :beneficio_bf, :beneficio_viva_leite, :beneficio_outro,

        :gestacao_gravidez,:gestacao_desejada, :gestacao_comentarios, :gestacao_mexer, :gestacao_prenatal, :gestacao_doencas, :gestacao_medicamentos,
        :gestacao_sobre,

        :nascimento_local, :nascimento_parto, :nascimento_peso, :nascimento_demorado, :nascimento_cordao, :nascimento_oxigenio,
        :nascimento_doencas,  :nascimento_posicao, :nascimento_reacoes, :nascimento_chorou, :nascimento_roxo, :nascimento_observacoes,

        :primeiro_relato, :primeiro_criado, :primeiro_doenca, :primeiro_alergia, :primeiro_rinite, :primeiro_asma, :primeiro_adenoide, :primeiro_bronquite, :primeiro_otite, :primeiro_garganta,
        :primeiro_bronco, :primeiros_outros, :primeiro_internado, :primeiro_epilepsia, :primeiro_convulsao, :primeiro_acidentes, :primeiro_sono, :primeiro_soliloquio, :primeiro_escoplesia,
        :primeiro_bruxismo, :primeiro_sonambulismo, :primeiro_pesadelo, :primeiro_ronco, :primeiro_baba, :primeiro_respira, :primeiro_transpira, :primeiro_eneurese, :primeiro_audicao,
        :primeiro_visao, :primeiro_unha, :primeiro_mao, :primeiro_boca, :primeiro_chupa, :primeiro_chupeta, :primeiros_outros, :primeiro_mamadeira, :primeiro_sexualidade, :primeiro_mamou, :primeiro_engolia,
        :primeiro_vomitava, :primeiro_engasgava, :primeiro_succao, :primeiros_outros, :primeiro_refluxo, :primeiro_amamentacao, :primeiro_mamadeira_01, :primeiro_inicio_alimentacao, :primeiro_concistencia,
        :primeiro_seio, :primeiro_mamadeira_02, :primeiro_rejeitou, :primeiro_tomada, :primeiro_super, :primeiro_solidos, :primeiro_atual, :primeiro_engolir, :primeiro_engolir_obs, :primeiro_fatos,
        :primeiro_sustentou, :primeiro_sentou, :primeiro_pe, :primeiro_andou, :primeiro_falou, :primeiro_trocas, :primeiro_engatinhou,

        :irmaos, :quantas, :idade, :antecedentes, :caracteristicas, :opiniao, :outra_natureza, :tipo_local, :irmao, :quantas, :idade, :antecedentes, :caracteristicas, 
        :opiniao, :outra_natureza, :tipo_local, :saude, :uso_medicamentos, :relatorio, :carteira_sus, :ciclo, :ra, :idpdi, :deficiencia, :data_fechamento_diagnostico,
        :escola_origem, :avatar

        )
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/views/alunos/_dados_familiares_s.html.erb
<div class="well well-sm"><h2>Dados Familiares</h2>
    <div class="row">

        <div class="col-xs-6 ">
              <div class="control-group">
                <%= "Nome" %>
                <div class="controls"><strong><%= @aluno.nome %></strong></div>
              </div>
        </div>

        <div class="col-md-4">

               <div class="control-group">
                <%= "Endereço" %>
                <div class="controls"><strong><%= @aluno.endereco %></strong></div>
              </div>
        </div>

        <div class="col-md-2">

              <div class="control-group">
                <%= "Número" %>
                <div class="controls"><strong><%= @aluno.numero %></strong></div>
              </div>
        </div>

    </div>

    <div class="row">

        <div class="col-xs-6">
              <div class="control-group">
                <%= "Bairro" %>
                <div class="controls">
                  <strong><%= @aluno.bairro %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-4">

               <div class="control-group">
                <%= "Cidade" %>
                <div class="controls">
                  <strong><%= @aluno.cidade %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-2">

              <div class="control-group">
                <%= "Estado" %>
                <div class="controls">
                  <strong><%= @aluno.estado %></strong>
                </div>
              </div>
        </div>

    </div>

    <div class="row">

        <div class="col-xs-6">
              <div class="control-group">
                <%= "Email" %>
                <div class="controls">
                  <strong><%= @aluno.email %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-2">

               <div class="control-group">
                <%= "Telefone" %>
                <div class="controls">
                  <strong><%= @aluno.telefone %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-2">

              <div class="control-group">
                <%= "Celular" %>
                <div class="controls">
                  <strong><%= @aluno.celular %></strong>
                </div>
              </div>
        </div>

		<div class="col-md-2">

              <div class="control-group">
                <%= "Ativo" %>
                <div class="controls">
                  <strong><%= @aluno.ativo %></strong>
                </div>
              </div>
        </div>

    </div>

    <div class="row">

        <div class="col-xs-3">
              <div class="control-group">
                <%= "R.G." %>
                <div class="controls">
                  <strong><%= @aluno.rg %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-3">

               <div class="control-group">
                <%= "C.P.F." %>
                <div class="controls">
                  <strong><%= @aluno.cpf %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-3">

              <div class="control-group">
                <%= "Data de Nascimento" %>
                <div class="controls">
                  <strong><%= @aluno.data_nascimento %></strong>
                </div>
              </div>
        </div>

		<div class="col-md-3">

              <div class="control-group">
                <%= "Data de Cadastro" %>
                <div class="controls">
                  <strong><%= @aluno.data_cadastro %></strong>
                </div>
              </div>
        </div>

    </div>

   <div class="row">

        <div class="col-xs-3">
              <div class="control-group">
                <%= "Naturalidade" %>
                <div class="controls">
                  <strong><%= @aluno.naturalidade %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-3">

               <div class="control-group">
                <%= "Ciclo" %>
                <div class="controls">
                  <strong><%= @aluno.ciclo%></strong>
                </div>
              </div>
        </div>

        <div class="col-md-3">

              <div class="control-group">
                <%= "R.A." %>
                <div class="controls">
                  <strong><%= @aluno.ra %></strong>
                </div>
              </div>
        </div>

		<div class="col-md-3">

              <div class="control-group">
                <%= "SIGM" %>
                <div class="controls">
                  <strong><%= @aluno.idpdi %></strong>
                </div>
              </div>
        </div>

    </div>
   <div class="row">

        <div class="col-xs-4">
              <div class="control-group">
                <%= "Deficiência" %>
                <div class="controls">
                  <strong><%= @aluno.deficiencia %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-4">

               <div class="control-group">
                <%= "Data Fechamento do Diagnóstico" %>
                <div class="controls">
                  <strong><%= @aluno.data_fechamento_diagnostico %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-4">

              <div class="control-group">
                <%= "Escola Origem" %>
                <div class="controls">
                  <strong><%= @aluno.escola_origem %></strong>
                </div>
              </div>
        </div>
	</div>


</div>
</div>

app/views/alunos/_dados_pessoais_s.html.erb
<div class="well well-sm"><h2>Dados do Aluno</h2>
    <div class="row">

        <div class="col-xs-6 ">
              <div class="control-group">
                <%= "Nome" %>
                <div class="controls"><strong><%= @aluno.nome %></strong></div>
              </div>
        </div>

        <div class="col-md-4">

               <div class="control-group">
                <%= "Endereço" %>
                <div class="controls"><strong><%= @aluno.endereco %></strong></div>
              </div>
        </div>

        <div class="col-md-2">

              <div class="control-group">
                <%= "Número" %>
                <div class="controls"><strong><%= @aluno.numero %></strong></div>
              </div>
        </div>

    </div>

    <div class="row">

        <div class="col-xs-6">
              <div class="control-group">
                <%= "Bairro" %>
                <div class="controls">
                  <strong><%= @aluno.bairro %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-4">

               <div class="control-group">
                <%= "Cidade" %>
                <div class="controls">
                  <strong><%= @aluno.cidade %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-2">

              <div class="control-group">
                <%= "Estado" %>
                <div class="controls">
                  <strong><%= @aluno.estado %></strong>
                </div>
              </div>
        </div>

    </div>

    <div class="row">

        <div class="col-xs-6">
              <div class="control-group">
                <%= "Email" %>
                <div class="controls">
                  <strong><%= @aluno.email %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-2">

               <div class="control-group">
                <%= "Telefone" %>
                <div class="controls">
                  <strong><%= @aluno.telefone %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-2">

              <div class="control-group">
                <%= "Celular" %>
                <div class="controls">
                  <strong><%= @aluno.celular %></strong>
                </div>
              </div>
        </div>

		<div class="col-md-2">

              <div class="control-group">
                <%= "Ativo" %>
                <div class="controls">
                  <strong><%= @aluno.ativo %></strong>
                </div>
              </div>
        </div>

    </div>

    <div class="row">

        <div class="col-xs-3">
              <div class="control-group">
                <%= "R.G." %>
                <div class="controls">
                  <strong><%= @aluno.rg %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-3">

               <div class="control-group">
                <%= "C.P.F." %>
                <div class="controls">
                  <strong><%= @aluno.cpf %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-3">

              <div class="control-group">
                <%= "Data de Nascimento" %>
                <div class="controls">
                  <strong><%= @aluno.data_nascimento %></strong>
                </div>
              </div>
        </div>

		<div class="col-md-3">

              <div class="control-group">
                <%= "Data de Cadastro" %>
                <div class="controls">
                  <strong><%= @aluno.data_cadastro %></strong>
                </div>
              </div>
        </div>

    </div>

   <div class="row">

        <div class="col-xs-3">
              <div class="control-group">
                <%= "Naturalidade" %>
                <div class="controls">
                  <strong><%= @aluno.naturalidade %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-3">

               <div class="control-group">
                <%= "Ciclo" %>
                <div class="controls">
                  <strong><%= @aluno.ciclo%></strong>
                </div>
              </div>
        </div>

        <div class="col-md-3">

              <div class="control-group">
                <%= "R.A." %>
                <div class="controls">
                  <strong><%= @aluno.ra %></strong>
                </div>
              </div>
        </div>

		<div class="col-md-3">

              <div class="control-group">
                <%= "SIGM" %>
                <div class="controls">
                  <strong><%= @aluno.idpdi %></strong>
                </div>
              </div>
        </div>

    </div>
   <div class="row">

        <div class="col-xs-4">
              <div class="control-group">
                <%= "Deficiência" %>
                <div class="controls">
                  <strong><%= @aluno.deficiencia %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-4">

               <div class="control-group">
                <%= "Data Fechamento do Diagnóstico" %>
                <div class="controls">
                  <strong><%= @aluno.data_fechamento_diagnostico %></strong>
                </div>
              </div>
        </div>

        <div class="col-md-4">

              <div class="control-group">
                <%= "Escola Origem" %>
                <div class="controls">
                  <strong><%= @aluno.escola_origem %></strong>
                </div>
              </div>
        </div>
	</div>


</div>
</div>

app/views/alunos/edit.html.erb
<%= render 'form' %>

app/views/alunos/index.html.erb
<%- model_class = Aluno -%><br>
<div class="panel panel-default" style="width: 80%; margin: 0 auto; ">
  <div class="panel-body"><h2> Listando Alunos</h2>
      <tr><%= will_paginate @alunos, renderer: BootstrapPagination::Rails %></tr>
    <table class="table table-striped" >
      <thead>
        <tr>
          <th><%= 'Código' %></th>
          <th><%= 'Nome' %></th>
          <th><%= 'Celular' %></th>
          <th><%= 'Telefone' %></th>
          <th><%= 'Ativo' %></th>
          <th><%= 'Criado em' %></th>
          <th><%= 'Ações' %></th>
        </tr>
      </thead>
      <tbody>
        <% @alunos.each do |aluno| %>
          <tr>
            <td width: 5% ><%= link_to aluno.id, aluno_path(aluno),:size => 13 %></td>
            <td width: 70%><%= aluno.nome %></td>
            <td width: 5% ><%= aluno.celular %></td>
            <td width: 5% ><%= aluno.telefone %></td>
            <td width: 5% ><%= aluno.ativo  %></td>
            <td width: 5% ><%= aluno.created_at.strftime("%d %b. %Y") %></td>
            <td width: 5% >
              <%= link_to 'Mostrar',aluno_path(aluno), :class => 'btn btn-primary btn-sm' %>
              <%= link_to 'Editar',edit_aluno_path(aluno), :class => 'btn btn-success btn-sm' %>
              <%= link_to 'Apagar',aluno_path(aluno),:method => :delete, data: { confirm: 'Você tem certeza?'},:class => 'btn btn-danger btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>
      <div class="panel panel-default">
        <div class="panel-body">
            <%= link_to 'Incluir novo Aluno',new_aluno_path,:class => 'btn btn-primary' %>
        </div>
      </div>

</div>

app/views/alunos/new.html.erb
<%= render 'form' %>