config/routes.rb
Rails.application.routes.draw do
  resources :pdialunos
  resources :alunos
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div id="header" class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">
            <i class="icon-reorder"></i>
        </button>
    <a class="navbar-brand brand" style="float: left; margin-top;" href="#"> <img src="/assets/Fotos/logo2.jpg"></a>
    <a class="navbar-brand" href="/">Instituto Norberto</a>
    <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>

    <nav class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li>
            <%= render 'layouts/navigation_links' %>
            </li>
        </ul>

    </nav>
</div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Editar Conta', edit_user_registration_path %></li>
  <li><%= link_to 'Sair', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Entrar', new_user_session_path %></li>
  <li><%= link_to 'Registrar', new_user_registration_path %></li>
  <li><%= link_to 'Alunos', alunos_path %></li>
 
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Usuários', users_path %></li>
    <li><%= link_to 'Alunos', alunos_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ins Nor" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ins Nor" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>